footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 2.0
publish_frequency: 3.0
transform_tolerance: 0.5

# resolution: 0.05
resolution: 0.1
always_send_full_costmap: False # so it publishes map_update topic


obstacle_range: 9.5
raytrace_range: 10.0



#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    footprint_clearing_enabled: False

    # observation_sources: laser
    # laser: {data_type: LaserScan, clearing: true, marking: true, topic: /scan, inf_is_valid: true}

    observation_sources: point_cloud_sensor
    point_cloud_sensor: {
        sensor_frame: os_lidar,
        data_type: PointCloud2, 
        # topic: /ouster/points, 
        # topic: /pc_out, # tests
        topic: /traversable_lidar, # Iana Traversability
        expected_update_rate: 15,   
        marking: true, 
        # clearing: true,
        clearing: false,
        
        min_obstacle_height: -0.2, #-0.08,
        max_obstacle_height: 1.5}


inflation:
        inflation_radius: 0.1 #0.20 # edited from 1.0
        # cost_scaling_factor: 10.0 # A scaling factor to apply to cost values during inflation. [def 10]
