controller_frequency: 5.0
recovery_behaviour_enabled: false # true

NavfnROS:
  allow_unknown: true # Specifies whether or not to allow navfn to create plans that traverse unknown space.
  default_tolerance: 0.2 #0.1 # A tolerance on the goal point for the planner.

DWAPlannerROS:
  # Robot configuration parameters  
  acc_lim_x: 2.5
  acc_lim_y: 0
  acc_lim_th: 3.2

  max_vel_x: 0.5
  min_vel_x: 0.0
  max_vel_y: 0.5
  min_vel_y: 0.0

  # Rotation: radians per second   Transl: m/s
  max_vel_trans: 0.4  # max is 1.0
  min_vel_trans: 0.05 #0.1
  max_vel_theta: 0.2  #0.15
  min_vel_theta: 0.02 #0.08


  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.1 #0.2
  latch_xy_goal_tolerance: false
